2015/03/23 20:00:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/index".' in C:\xampp\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/index')
#1 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/siak/index.php/gii/index
---
2015/03/25 21:04:54 [error] [exception.CException] exception 'CException' with message 'CUrlManager.UrlFormat must be either "path" or "get".' in C:\xampp\yii\framework\web\CUrlManager.php:511
Stack trace:
#0 C:\xampp\yii\framework\base\CComponent.php(152): CUrlManager->setUrlFormat('path  ')
#1 C:\xampp\yii\framework\YiiBase.php(220): CComponent->__set('urlFormat', 'path  ')
#2 C:\xampp\yii\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#3 C:\xampp\yii\framework\base\CApplication.php(530): CModule->getComponent('urlManager')
#4 C:\xampp\yii\framework\web\CWebApplication.php(140): CApplication->getUrlManager()
#5 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#6 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/siak/index.php/gii/default/login
HTTP_REFERER=http://localhost/siak/index.php/gii/default/login
---
2015/03/25 21:05:48 [error] [exception.CException] exception 'CException' with message 'CUrlManager.UrlFormat must be either "path" or "get".' in C:\xampp\yii\framework\web\CUrlManager.php:511
Stack trace:
#0 C:\xampp\yii\framework\base\CComponent.php(152): CUrlManager->setUrlFormat('path  ')
#1 C:\xampp\yii\framework\YiiBase.php(220): CComponent->__set('urlFormat', 'path  ')
#2 C:\xampp\yii\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#3 C:\xampp\yii\framework\base\CApplication.php(530): CModule->getComponent('urlManager')
#4 C:\xampp\yii\framework\web\CWebApplication.php(140): CApplication->getUrlManager()
#5 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#6 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/siak/index.php/gii/default/login
---
2015/03/25 21:05:51 [error] [exception.CException] exception 'CException' with message 'CUrlManager.UrlFormat must be either "path" or "get".' in C:\xampp\yii\framework\web\CUrlManager.php:511
Stack trace:
#0 C:\xampp\yii\framework\base\CComponent.php(152): CUrlManager->setUrlFormat('path  ')
#1 C:\xampp\yii\framework\YiiBase.php(220): CComponent->__set('urlFormat', 'path  ')
#2 C:\xampp\yii\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#3 C:\xampp\yii\framework\base\CApplication.php(530): CModule->getComponent('urlManager')
#4 C:\xampp\yii\framework\web\CWebApplication.php(140): CApplication->getUrlManager()
#5 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#6 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/siak/index.php/gii/default/
---
2015/03/25 21:06:10 [error] [exception.CException] exception 'CException' with message 'CUrlManager.UrlFormat must be either "path" or "get".' in C:\xampp\yii\framework\web\CUrlManager.php:511
Stack trace:
#0 C:\xampp\yii\framework\base\CComponent.php(152): CUrlManager->setUrlFormat('path  ')
#1 C:\xampp\yii\framework\YiiBase.php(220): CComponent->__set('urlFormat', 'path  ')
#2 C:\xampp\yii\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#3 C:\xampp\yii\framework\base\CApplication.php(530): CModule->getComponent('urlManager')
#4 C:\xampp\yii\framework\web\CWebApplication.php(140): CApplication->getUrlManager()
#5 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#6 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/siak/index.php/gii/default/login
---
2015/03/25 21:11:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/siak/index.php/gii/model/index
HTTP_REFERER=http://localhost/siak/index.php/gii/default/index
---
2015/03/25 21:12:35 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/siak/index.php/gii/model/index
HTTP_REFERER=http://localhost/siak/index.php/gii/default/index
---
2015/03/25 21:15:53 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'siakdb'' in C:\xampp\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/siak/index.php/gii/model/index
HTTP_REFERER=http://localhost/siak/index.php/gii/default/index
---
2015/03/25 21:15:57 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'siakdb'' in C:\xampp\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/siak/index.php/gii/model/index
HTTP_REFERER=http://localhost/siak/index.php/gii/default/index
---
2015/03/25 22:05:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "usr".' in C:\xampp\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('usr')
#1 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/siak/index.php/usr
---
2015/04/03 01:38:23 [error] [php] Undefined variable: role (C:\xampp\htdocs\siak\protected\views\user\_form.php:44)
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(869): UserController->renderFile()
#1 C:\xampp\htdocs\siak\protected\views\user\create.php(18): UserController->renderPartial()
#2 C:\xampp\yii\framework\web\CBaseController.php(126): require()
#3 C:\xampp\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#4 C:\xampp\yii\framework\web\CController.php(869): UserController->renderFile()
#5 C:\xampp\yii\framework\web\CController.php(782): UserController->renderPartial()
#6 C:\xampp\htdocs\siak\protected\controllers\UserController.php(79): UserController->render()
#7 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#8 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#10 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#11 C:\xampp\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#12 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#13 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#14 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#15 C:\xampp\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#16 C:\xampp\yii\framework\web\CWebApplication.php(282): UserController->run()
#17 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#18 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#19 C:\xampp\htdocs\siak\index.php(13): CWebApplication->run()
REQUEST_URI=/siak/index.php/user/create
in C:\xampp\htdocs\siak\protected\views\user\_form.php (44)
in C:\xampp\htdocs\siak\protected\views\user\create.php (18)
in C:\xampp\htdocs\siak\protected\controllers\UserController.php (79)
2015/04/03 01:38:58 [error] [php] Undefined variable: models (C:\xampp\htdocs\siak\protected\views\user\_form.php:43)
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(869): UserController->renderFile()
#1 C:\xampp\htdocs\siak\protected\views\user\create.php(18): UserController->renderPartial()
#2 C:\xampp\yii\framework\web\CBaseController.php(126): require()
#3 C:\xampp\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#4 C:\xampp\yii\framework\web\CController.php(869): UserController->renderFile()
#5 C:\xampp\yii\framework\web\CController.php(782): UserController->renderPartial()
#6 C:\xampp\htdocs\siak\protected\controllers\UserController.php(79): UserController->render()
#7 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#8 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#10 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#11 C:\xampp\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#12 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#13 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#14 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#15 C:\xampp\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#16 C:\xampp\yii\framework\web\CWebApplication.php(282): UserController->run()
#17 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#18 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#19 C:\xampp\htdocs\siak\index.php(13): CWebApplication->run()
REQUEST_URI=/siak/index.php/user/create
in C:\xampp\htdocs\siak\protected\views\user\_form.php (43)
in C:\xampp\htdocs\siak\protected\views\user\create.php (18)
in C:\xampp\htdocs\siak\protected\controllers\UserController.php (79)
2015/04/03 01:51:04 [error] [exception.CException] exception 'CException' with message 'UserController and its behaviors do not have a method or closure named "getRoleOption".' in C:\xampp\yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\siak\protected\views\user\_form.php(43): CComponent->__call('getRoleOption', Array)
#1 C:\xampp\htdocs\siak\protected\views\user\_form.php(43): UserController->getRoleOption()
#2 C:\xampp\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\siak\protected\views\user\create.php(18): CController->renderPartial('_form', Array)
#6 C:\xampp\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\yii\framework\web\CController.php(782): CController->renderPartial('create', Array, true)
#10 C:\xampp\htdocs\siak\protected\controllers\UserController.php(79): CController->render('create', Array)
#11 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#12 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('create')
#21 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#22 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#23 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/siak/index.php/user/create
HTTP_REFERER=http://localhost/siak/index.php/user
---
2015/04/03 01:51:30 [error] [exception.CException] exception 'CException' with message 'Property "Role.findAll" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('findAll')
#1 C:\xampp\htdocs\siak\protected\models\User.php(108): CActiveRecord->__get('findAll')
#2 C:\xampp\htdocs\siak\protected\views\user\_form.php(43): User->getRoleOption()
#3 C:\xampp\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#4 C:\xampp\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#6 C:\xampp\htdocs\siak\protected\views\user\create.php(18): CController->renderPartial('_form', Array)
#7 C:\xampp\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#8 C:\xampp\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#10 C:\xampp\yii\framework\web\CController.php(782): CController->renderPartial('create', Array, true)
#11 C:\xampp\htdocs\siak\protected\controllers\UserController.php(79): CController->render('create', Array)
#12 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#13 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#14 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#15 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#16 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#17 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#18 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#19 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#20 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#21 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('create')
#22 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#23 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#24 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#25 {main}
REQUEST_URI=/siak/index.php/user/create
HTTP_REFERER=http://localhost/siak/index.php/user
---
2015/04/03 01:52:38 [error] [exception.CException] exception 'CException' with message 'Property "Role.findAll" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('findAll')
#1 C:\xampp\htdocs\siak\protected\models\User.php(108): CActiveRecord->__get('findAll')
#2 C:\xampp\htdocs\siak\protected\views\user\_form.php(43): User->getRoleOption()
#3 C:\xampp\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#4 C:\xampp\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#6 C:\xampp\htdocs\siak\protected\views\user\create.php(18): CController->renderPartial('_form', Array)
#7 C:\xampp\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#8 C:\xampp\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#10 C:\xampp\yii\framework\web\CController.php(782): CController->renderPartial('create', Array, true)
#11 C:\xampp\htdocs\siak\protected\controllers\UserController.php(79): CController->render('create', Array)
#12 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#13 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#14 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#15 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#16 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#17 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#18 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#19 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#20 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#21 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('create')
#22 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#23 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#24 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#25 {main}
REQUEST_URI=/siak/index.php/user/create
HTTP_REFERER=http://localhost/siak/index.php/user
---
2015/04/03 01:53:25 [error] [php] Missing argument 2 for CHtml::listData(), called in C:\xampp\htdocs\siak\protected\models\User.php on line 108 and defined (C:\xampp\yii\framework\web\helpers\CHtml.php:2270)
Stack trace:
#0 C:\xampp\yii\framework\web\CBaseController.php(126): require()
#1 C:\xampp\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#2 C:\xampp\yii\framework\web\CController.php(869): UserController->renderFile()
#3 C:\xampp\htdocs\siak\protected\views\user\create.php(18): UserController->renderPartial()
#4 C:\xampp\yii\framework\web\CBaseController.php(126): require()
#5 C:\xampp\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#6 C:\xampp\yii\framework\web\CController.php(869): UserController->renderFile()
#7 C:\xampp\yii\framework\web\CController.php(782): UserController->renderPartial()
#8 C:\xampp\htdocs\siak\protected\controllers\UserController.php(79): UserController->render()
#9 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#10 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#11 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#12 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#14 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#15 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#16 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#18 C:\xampp\yii\framework\web\CWebApplication.php(282): UserController->run()
#19 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#20 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#21 C:\xampp\htdocs\siak\index.php(13): CWebApplication->run()
REQUEST_URI=/siak/index.php/user/create
in C:\xampp\htdocs\siak\protected\models\User.php (108)
in C:\xampp\htdocs\siak\protected\views\user\_form.php (43)
in C:\xampp\htdocs\siak\protected\views\user\create.php (18)
2015/04/03 01:56:08 [error] [php] call_user_func() expects parameter 1 to be a valid callback, array must have exactly two members (C:\xampp\yii\framework\web\helpers\CHtml.php:2340)
Stack trace:
#0 C:\xampp\htdocs\siak\protected\models\User.php(108): listData()
#1 C:\xampp\htdocs\siak\protected\views\user\_form.php(43): User->getRoleOption()
#2 C:\xampp\yii\framework\web\CBaseController.php(126): require()
#3 C:\xampp\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#4 C:\xampp\yii\framework\web\CController.php(869): UserController->renderFile()
#5 C:\xampp\htdocs\siak\protected\views\user\create.php(18): UserController->renderPartial()
#6 C:\xampp\yii\framework\web\CBaseController.php(126): require()
#7 C:\xampp\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#8 C:\xampp\yii\framework\web\CController.php(869): UserController->renderFile()
#9 C:\xampp\yii\framework\web\CController.php(782): UserController->renderPartial()
#10 C:\xampp\htdocs\siak\protected\controllers\UserController.php(79): UserController->render()
#11 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#12 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#13 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#14 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#16 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#17 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#18 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#20 C:\xampp\yii\framework\web\CWebApplication.php(282): UserController->run()
#21 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#22 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#23 C:\xampp\htdocs\siak\index.php(13): CWebApplication->run()
REQUEST_URI=/siak/index.php/user/create
in C:\xampp\htdocs\siak\protected\models\User.php (108)
in C:\xampp\htdocs\siak\protected\views\user\_form.php (43)
in C:\xampp\htdocs\siak\protected\views\user\create.php (18)
2015/04/03 01:56:40 [error] [php] call_user_func() expects parameter 1 to be a valid callback, array must have exactly two members (C:\xampp\yii\framework\web\helpers\CHtml.php:2340)
Stack trace:
#0 C:\xampp\htdocs\siak\protected\models\User.php(108): listData()
#1 C:\xampp\htdocs\siak\protected\views\user\_form.php(43): User->getRoleOption()
#2 C:\xampp\yii\framework\web\CBaseController.php(126): require()
#3 C:\xampp\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#4 C:\xampp\yii\framework\web\CController.php(869): UserController->renderFile()
#5 C:\xampp\htdocs\siak\protected\views\user\create.php(18): UserController->renderPartial()
#6 C:\xampp\yii\framework\web\CBaseController.php(126): require()
#7 C:\xampp\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#8 C:\xampp\yii\framework\web\CController.php(869): UserController->renderFile()
#9 C:\xampp\yii\framework\web\CController.php(782): UserController->renderPartial()
#10 C:\xampp\htdocs\siak\protected\controllers\UserController.php(79): UserController->render()
#11 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#12 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#13 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#14 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#16 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#17 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#18 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#20 C:\xampp\yii\framework\web\CWebApplication.php(282): UserController->run()
#21 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#22 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#23 C:\xampp\htdocs\siak\index.php(13): CWebApplication->run()
REQUEST_URI=/siak/index.php/user/create
in C:\xampp\htdocs\siak\protected\models\User.php (108)
in C:\xampp\htdocs\siak\protected\views\user\_form.php (43)
in C:\xampp\htdocs\siak\protected\views\user\create.php (18)
2015/04/03 01:56:41 [error] [php] call_user_func() expects parameter 1 to be a valid callback, array must have exactly two members (C:\xampp\yii\framework\web\helpers\CHtml.php:2340)
Stack trace:
#0 C:\xampp\htdocs\siak\protected\models\User.php(108): listData()
#1 C:\xampp\htdocs\siak\protected\views\user\_form.php(43): User->getRoleOption()
#2 C:\xampp\yii\framework\web\CBaseController.php(126): require()
#3 C:\xampp\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#4 C:\xampp\yii\framework\web\CController.php(869): UserController->renderFile()
#5 C:\xampp\htdocs\siak\protected\views\user\create.php(18): UserController->renderPartial()
#6 C:\xampp\yii\framework\web\CBaseController.php(126): require()
#7 C:\xampp\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#8 C:\xampp\yii\framework\web\CController.php(869): UserController->renderFile()
#9 C:\xampp\yii\framework\web\CController.php(782): UserController->renderPartial()
#10 C:\xampp\htdocs\siak\protected\controllers\UserController.php(79): UserController->render()
#11 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#12 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#13 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#14 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#16 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#17 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#18 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#20 C:\xampp\yii\framework\web\CWebApplication.php(282): UserController->run()
#21 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#22 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#23 C:\xampp\htdocs\siak\index.php(13): CWebApplication->run()
REQUEST_URI=/siak/index.php/user/create
in C:\xampp\htdocs\siak\protected\models\User.php (108)
in C:\xampp\htdocs\siak\protected\views\user\_form.php (43)
in C:\xampp\htdocs\siak\protected\views\user\create.php (18)
2015/04/03 01:56:41 [error] [php] call_user_func() expects parameter 1 to be a valid callback, array must have exactly two members (C:\xampp\yii\framework\web\helpers\CHtml.php:2340)
Stack trace:
#0 C:\xampp\htdocs\siak\protected\models\User.php(108): listData()
#1 C:\xampp\htdocs\siak\protected\views\user\_form.php(43): User->getRoleOption()
#2 C:\xampp\yii\framework\web\CBaseController.php(126): require()
#3 C:\xampp\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#4 C:\xampp\yii\framework\web\CController.php(869): UserController->renderFile()
#5 C:\xampp\htdocs\siak\protected\views\user\create.php(18): UserController->renderPartial()
#6 C:\xampp\yii\framework\web\CBaseController.php(126): require()
#7 C:\xampp\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#8 C:\xampp\yii\framework\web\CController.php(869): UserController->renderFile()
#9 C:\xampp\yii\framework\web\CController.php(782): UserController->renderPartial()
#10 C:\xampp\htdocs\siak\protected\controllers\UserController.php(79): UserController->render()
#11 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#12 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#13 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#14 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#16 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#17 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#18 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#20 C:\xampp\yii\framework\web\CWebApplication.php(282): UserController->run()
#21 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#22 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#23 C:\xampp\htdocs\siak\index.php(13): CWebApplication->run()
REQUEST_URI=/siak/index.php/user/create
in C:\xampp\htdocs\siak\protected\models\User.php (108)
in C:\xampp\htdocs\siak\protected\views\user\_form.php (43)
in C:\xampp\htdocs\siak\protected\views\user\create.php (18)
2015/04/03 01:56:42 [error] [php] call_user_func() expects parameter 1 to be a valid callback, array must have exactly two members (C:\xampp\yii\framework\web\helpers\CHtml.php:2340)
Stack trace:
#0 C:\xampp\htdocs\siak\protected\models\User.php(108): listData()
#1 C:\xampp\htdocs\siak\protected\views\user\_form.php(43): User->getRoleOption()
#2 C:\xampp\yii\framework\web\CBaseController.php(126): require()
#3 C:\xampp\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#4 C:\xampp\yii\framework\web\CController.php(869): UserController->renderFile()
#5 C:\xampp\htdocs\siak\protected\views\user\create.php(18): UserController->renderPartial()
#6 C:\xampp\yii\framework\web\CBaseController.php(126): require()
#7 C:\xampp\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#8 C:\xampp\yii\framework\web\CController.php(869): UserController->renderFile()
#9 C:\xampp\yii\framework\web\CController.php(782): UserController->renderPartial()
#10 C:\xampp\htdocs\siak\protected\controllers\UserController.php(79): UserController->render()
#11 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#12 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#13 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#14 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#16 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#17 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#18 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#20 C:\xampp\yii\framework\web\CWebApplication.php(282): UserController->run()
#21 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#22 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#23 C:\xampp\htdocs\siak\index.php(13): CWebApplication->run()
REQUEST_URI=/siak/index.php/user/create
in C:\xampp\htdocs\siak\protected\models\User.php (108)
in C:\xampp\htdocs\siak\protected\views\user\_form.php (43)
in C:\xampp\htdocs\siak\protected\views\user\create.php (18)
2015/04/03 02:05:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551dd93d2d839
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 02:05:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428019517367
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 02:05:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428019517368
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 02:05:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428019517369
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 02:05:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428019517370
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 02:05:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551dd946c413a
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 02:07:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551dd9cc99cf4
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 02:07:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551dd9cdbb793
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 02:20:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551ddcd6a1d7f
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:10:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551e12b995b12
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:10:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428034233733
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:10:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428034233734
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:10:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428034233735
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:10:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428034233736
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:10:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428034233737
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:10:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428034233738
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:10:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428034233739
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:10:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428034233740
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:10:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428034233741
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:14:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551e13ad5ebd9
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:14:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551e13ae2ed82
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:14:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428034478273
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:14:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428034478274
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:14:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428034478275
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:16:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551e141154d85
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:17:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551e146579366
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:24:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551e15ef603ef
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:24:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551e15f046f1b
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:32:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551e17eb8c002
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:32:52 [error] [exception.CException] exception 'CException' with message 'Property "User.saltPassword" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(161): CComponent->__set('saltPassword', '551e17f4f1d022....')
#1 C:\xampp\htdocs\siak\protected\controllers\UserController.php(75): CActiveRecord->__set('saltPassword', '551e17f4f1d022....')
#2 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#3 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('create')
#12 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#13 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/siak/index.php/user/create
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:33:38 [error] [exception.CException] exception 'CException' with message 'Property "User.saltPassword" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(161): CComponent->__set('saltPassword', '551e1822e5cbf7....')
#1 C:\xampp\htdocs\siak\protected\controllers\UserController.php(75): CActiveRecord->__set('saltPassword', '551e1822e5cbf7....')
#2 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#3 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('create')
#12 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#13 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/siak/index.php/user/create
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:33:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551e18242393c
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:33:51 [error] [exception.CException] exception 'CException' with message 'Property "User.saltPassword" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(161): CComponent->__set('saltPassword', '551e182f43f0f5....')
#1 C:\xampp\htdocs\siak\protected\controllers\UserController.php(75): CActiveRecord->__set('saltPassword', '551e182f43f0f5....')
#2 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#3 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('create')
#12 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#13 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/siak/index.php/user/create
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:35:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551e188d7510c
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:35:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551e188f1e84e
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 06:36:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551e18c582837
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 07:39:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551e27ac1d7dc
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 07:40:14 [error] [exception.CException] exception 'CException' with message 'Property "User.saltPassword" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(161): CComponent->__set('saltPassword', '551e27be0a3400....')
#1 C:\xampp\htdocs\siak\protected\controllers\UserController.php(75): CActiveRecord->__set('saltPassword', '551e27be0a3400....')
#2 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#3 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('create')
#12 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#13 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/siak/index.php/user/create
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 12:31:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#3 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551e6c0927faf
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 12:31:48 [error] [exception.CException] exception 'CException' with message 'CCaptchaValidator.action "captcha" is invalid. Unable to find such an action in the current controller.' in C:\xampp\yii\framework\validators\CCaptchaValidator.php:77
Stack trace:
#0 C:\xampp\yii\framework\validators\CCaptchaValidator.php(49): CCaptchaValidator->getCaptchaAction()
#1 C:\xampp\yii\framework\validators\CValidator.php(201): CCaptchaValidator->validateAttribute(Object(User), 'verifyCode')
#2 C:\xampp\yii\framework\base\CModel.php(159): CValidator->validate(Object(User), NULL)
#3 C:\xampp\yii\framework\db\ar\CActiveRecord.php(808): CModel->validate(NULL)
#4 C:\xampp\htdocs\siak\protected\controllers\UserController.php(77): CActiveRecord->save()
#5 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#6 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#8 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#9 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#10 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#11 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#12 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#13 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('create')
#15 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#16 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#17 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/siak/index.php/user/create
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 12:38:35 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CCaptchaAction), Array)
#7 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#8 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#9 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551e6dab601fb
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 12:38:46 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CCaptchaAction), Array)
#7 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#8 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#9 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551e6db642665
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 12:38:54 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CCaptchaAction), Array)
#7 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#8 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#9 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428057526425
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 12:38:56 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CCaptchaAction), Array)
#7 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#8 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#9 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428057526426
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 12:44:06 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CCaptchaAction), Array)
#7 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#8 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#9 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551e6ef66047a
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 12:44:25 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CCaptchaAction), Array)
#7 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#8 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#9 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551e6f08d4457
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 12:44:33 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CCaptchaAction), Array)
#7 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#8 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#9 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428057864962
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 12:44:34 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CCaptchaAction), Array)
#7 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#8 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#9 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428057864963
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 12:44:34 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CCaptchaAction), Array)
#7 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#8 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#9 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428057864964
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 12:44:34 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CCaptchaAction), Array)
#7 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#8 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#9 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428057864965
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 12:46:47 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CCaptchaAction), Array)
#7 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#8 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#9 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siak/index.php/user/captcha?v=551e6f97be69f
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 12:46:55 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CCaptchaAction), Array)
#7 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#8 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#9 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428058007882
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 12:46:56 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CCaptchaAction), Array)
#7 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#8 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#9 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428058007883
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 12:46:56 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CCaptchaAction), Array)
#7 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('captcha')
#8 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/captcha')
#9 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siak/index.php/user/captcha?refresh=1&_=1428058007884
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 12:48:02 [error] [exception.CException] exception 'CException' with message 'Property "User.verifyCode" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('verifyCode')
#1 C:\xampp\yii\framework\validators\CRequiredValidator.php(58): CActiveRecord->__get('verifyCode')
#2 C:\xampp\yii\framework\validators\CValidator.php(201): CRequiredValidator->validateAttribute(Object(User), 'verifyCode')
#3 C:\xampp\yii\framework\base\CModel.php(159): CValidator->validate(Object(User), NULL)
#4 C:\xampp\yii\framework\db\ar\CActiveRecord.php(808): CModel->validate(NULL)
#5 C:\xampp\htdocs\siak\protected\controllers\UserController.php(77): CActiveRecord->save()
#6 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#7 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('create')
#16 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#17 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#18 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/siak/index.php/user/create
HTTP_REFERER=http://localhost/siak/index.php/user/create
---
2015/04/03 12:54:14 [error] [exception.CException] exception 'CException' with message 'Property "User.nama" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('nama')
#1 C:\xampp\htdocs\siak\protected\views\user\_view.php(17): CActiveRecord->__get('nama')
#2 C:\xampp\yii\framework\web\CBaseController.php(130): require('C:\\xampp\\htdocs...')
#3 C:\xampp\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, false)
#4 C:\xampp\yii\framework\zii\widgets\CListView.php(291): CBaseController->renderFile('C:\\xampp\\htdocs...', Array)
#5 C:\xampp\yii\framework\zii\widgets\CBaseListView.php(181): CListView->renderItems()
#6 [internal function]: CBaseListView->renderSection(Array)
#7 C:\xampp\yii\framework\zii\widgets\CBaseListView.php(164): preg_replace_callback('/{(\\w+)}/', Array, '{summary}\n{sort...')
#8 C:\xampp\yii\framework\zii\widgets\CBaseListView.php(149): CBaseListView->renderContent()
#9 C:\xampp\yii\framework\web\CBaseController.php(181): CBaseListView->run()
#10 C:\xampp\htdocs\siak\protected\views\user\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#11 C:\xampp\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#12 C:\xampp\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#15 C:\xampp\htdocs\siak\protected\controllers\UserController.php(132): CController->render('index', Array)
#16 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionIndex()
#17 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#19 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#20 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#21 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#22 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#23 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#24 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#25 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('')
#26 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user')
#27 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#28 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#29 {main}
REQUEST_URI=/siak/index.php/user
---
2015/04/03 12:54:26 [error] [exception.CException] exception 'CException' with message 'Property "User.nama" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('nama')
#1 C:\xampp\htdocs\siak\protected\views\user\_view.php(17): CActiveRecord->__get('nama')
#2 C:\xampp\yii\framework\web\CBaseController.php(130): require('C:\\xampp\\htdocs...')
#3 C:\xampp\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, false)
#4 C:\xampp\yii\framework\zii\widgets\CListView.php(291): CBaseController->renderFile('C:\\xampp\\htdocs...', Array)
#5 C:\xampp\yii\framework\zii\widgets\CBaseListView.php(181): CListView->renderItems()
#6 [internal function]: CBaseListView->renderSection(Array)
#7 C:\xampp\yii\framework\zii\widgets\CBaseListView.php(164): preg_replace_callback('/{(\\w+)}/', Array, '{summary}\n{sort...')
#8 C:\xampp\yii\framework\zii\widgets\CBaseListView.php(149): CBaseListView->renderContent()
#9 C:\xampp\yii\framework\web\CBaseController.php(181): CBaseListView->run()
#10 C:\xampp\htdocs\siak\protected\views\user\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#11 C:\xampp\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#12 C:\xampp\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#15 C:\xampp\htdocs\siak\protected\controllers\UserController.php(132): CController->render('index', Array)
#16 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionIndex()
#17 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#19 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#20 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#21 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#22 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#23 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#24 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#25 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('')
#26 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user')
#27 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#28 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#29 {main}
REQUEST_URI=/siak/index.php/user/
---
2015/04/03 13:05:52 [error] [exception.CException] exception 'CException' with message 'Property "User.id" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('id')
#1 C:\xampp\htdocs\siak\protected\components\UserIdentity.php(28): CActiveRecord->__get('id')
#2 C:\xampp\htdocs\siak\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\siak\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/siak/index.php/site/login
HTTP_REFERER=http://localhost/siak/index.php/site/login
---
2015/04/03 13:08:06 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.id" is read only.' in C:\xampp\yii\framework\base\CComponent.php:170
Stack trace:
#0 C:\xampp\htdocs\siak\protected\components\UserIdentity.php(28): CComponent->__set('id', '1')
#1 C:\xampp\htdocs\siak\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\siak\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/siak/index.php/site/login
HTTP_REFERER=http://localhost/siak/index.php/site/login
---
2015/04/03 13:08:38 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.id_user" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\siak\protected\components\UserIdentity.php(28): CComponent->__set('id_user', '1')
#1 C:\xampp\htdocs\siak\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\siak\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/siak/index.php/site/login
HTTP_REFERER=http://localhost/siak/index.php/site/login
---
2015/04/03 13:08:55 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.id" is read only.' in C:\xampp\yii\framework\base\CComponent.php:170
Stack trace:
#0 C:\xampp\htdocs\siak\protected\components\UserIdentity.php(28): CComponent->__set('id', '1')
#1 C:\xampp\htdocs\siak\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\siak\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/siak/index.php/site/login
HTTP_REFERER=http://localhost/siak/index.php/site/login
---
2015/04/03 13:09:08 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.id" is read only.' in C:\xampp\yii\framework\base\CComponent.php:170
Stack trace:
#0 C:\xampp\htdocs\siak\protected\components\UserIdentity.php(28): CComponent->__set('id', '1')
#1 C:\xampp\htdocs\siak\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\siak\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/siak/index.php/site/login
HTTP_REFERER=http://localhost/siak/index.php/site/login
---
2015/04/03 13:09:17 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.id" is read only.' in C:\xampp\yii\framework\base\CComponent.php:170
Stack trace:
#0 C:\xampp\htdocs\siak\protected\components\UserIdentity.php(28): CComponent->__set('id', '1')
#1 C:\xampp\htdocs\siak\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\siak\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/siak/index.php/site/login
HTTP_REFERER=http://localhost/siak/index.php/site/login
---
2015/04/03 13:10:15 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.id" is read only.' in C:\xampp\yii\framework\base\CComponent.php:170
Stack trace:
#0 C:\xampp\htdocs\siak\protected\components\UserIdentity.php(28): CComponent->__set('id', '1')
#1 C:\xampp\htdocs\siak\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\siak\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/siak/index.php/site/login
HTTP_REFERER=http://localhost/siak/index.php/site/login
---
2015/04/03 13:10:20 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.id" is read only.' in C:\xampp\yii\framework\base\CComponent.php:170
Stack trace:
#0 C:\xampp\htdocs\siak\protected\components\UserIdentity.php(28): CComponent->__set('id', '1')
#1 C:\xampp\htdocs\siak\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\siak\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/siak/index.php/site/login
HTTP_REFERER=http://localhost/siak/index.php/site/login
---
2015/04/03 13:13:41 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.id" is read only.' in C:\xampp\yii\framework\base\CComponent.php:170
Stack trace:
#0 C:\xampp\htdocs\siak\protected\components\UserIdentity.php(28): CComponent->__set('id', '1')
#1 C:\xampp\htdocs\siak\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\siak\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/siak/index.php/site/login
HTTP_REFERER=http://localhost/siak/index.php/site/login
---
2015/04/03 13:14:48 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.id" is read only.' in C:\xampp\yii\framework\base\CComponent.php:170
Stack trace:
#0 C:\xampp\htdocs\siak\protected\components\UserIdentity.php(28): CComponent->__set('id', '1')
#1 C:\xampp\htdocs\siak\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\siak\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/siak/index.php/site/login
HTTP_REFERER=http://localhost/siak/index.php/site/login
---
2015/04/03 13:32:26 [error] [php] Undefined variable: user (C:\xampp\htdocs\siak\protected\components\UserIdentity.php:25)
Stack trace:
#0 C:\xampp\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#1 C:\xampp\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\siak\protected\controllers\SiteController.php(94): LoginForm->validate()
#3 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siak\index.php(13): CWebApplication->run()
REQUEST_URI=/siak/index.php/site/login
in C:\xampp\htdocs\siak\protected\components\UserIdentity.php (25)
in C:\xampp\htdocs\siak\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\siak\protected\controllers\SiteController.php (94)
2015/04/03 13:32:36 [error] [php] Undefined variable: user (C:\xampp\htdocs\siak\protected\components\UserIdentity.php:25)
Stack trace:
#0 C:\xampp\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#1 C:\xampp\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\siak\protected\controllers\SiteController.php(94): LoginForm->validate()
#3 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siak\index.php(13): CWebApplication->run()
REQUEST_URI=/siak/index.php/site/login
in C:\xampp\htdocs\siak\protected\components\UserIdentity.php (25)
in C:\xampp\htdocs\siak\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\siak\protected\controllers\SiteController.php (94)
2015/04/03 13:33:05 [error] [php] Undefined variable: user (C:\xampp\htdocs\siak\protected\components\UserIdentity.php:25)
Stack trace:
#0 C:\xampp\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#1 C:\xampp\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\siak\protected\controllers\SiteController.php(94): LoginForm->validate()
#3 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siak\index.php(13): CWebApplication->run()
REQUEST_URI=/siak/index.php/site/login
in C:\xampp\htdocs\siak\protected\components\UserIdentity.php (25)
in C:\xampp\htdocs\siak\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\siak\protected\controllers\SiteController.php (94)
2015/04/03 13:33:10 [error] [php] Undefined variable: user (C:\xampp\htdocs\siak\protected\components\UserIdentity.php:25)
Stack trace:
#0 C:\xampp\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#1 C:\xampp\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\siak\protected\controllers\SiteController.php(94): LoginForm->validate()
#3 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siak\index.php(13): CWebApplication->run()
REQUEST_URI=/siak/index.php/site/login
in C:\xampp\htdocs\siak\protected\components\UserIdentity.php (25)
in C:\xampp\htdocs\siak\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\siak\protected\controllers\SiteController.php (94)
2015/04/03 13:33:24 [error] [exception.CException] exception 'CException' with message 'Property "User.id" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('id')
#1 C:\xampp\htdocs\siak\protected\components\UserIdentity.php(29): CActiveRecord->__get('id')
#2 C:\xampp\htdocs\siak\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\siak\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/siak/index.php/site/login
HTTP_REFERER=http://localhost/siak/index.php/site/login
---
2015/04/03 13:33:42 [error] [exception.CException] exception 'CException' with message 'Property "User.title" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('title')
#1 C:\xampp\htdocs\siak\protected\components\UserIdentity.php(30): CActiveRecord->__get('title')
#2 C:\xampp\htdocs\siak\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\siak\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/siak/index.php/site/login
HTTP_REFERER=http://localhost/siak/index.php/site/login
---
2015/04/03 13:34:06 [error] [php] Undefined variable: user (C:\xampp\htdocs\siak\protected\components\UserIdentity.php:30)
Stack trace:
#0 C:\xampp\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#1 C:\xampp\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\siak\protected\controllers\SiteController.php(94): LoginForm->validate()
#3 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siak\index.php(13): CWebApplication->run()
REQUEST_URI=/siak/index.php/site/login
in C:\xampp\htdocs\siak\protected\components\UserIdentity.php (30)
in C:\xampp\htdocs\siak\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\siak\protected\controllers\SiteController.php (94)
2015/04/03 13:34:12 [error] [php] Undefined variable: user (C:\xampp\htdocs\siak\protected\components\UserIdentity.php:30)
Stack trace:
#0 C:\xampp\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#1 C:\xampp\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\siak\protected\controllers\SiteController.php(94): LoginForm->validate()
#3 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siak\index.php(13): CWebApplication->run()
REQUEST_URI=/siak/index.php/site/login
in C:\xampp\htdocs\siak\protected\components\UserIdentity.php (30)
in C:\xampp\htdocs\siak\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\siak\protected\controllers\SiteController.php (94)
2015/04/03 13:35:25 [error] [exception.CException] exception 'CException' with message 'Property "User.id" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('id')
#1 C:\xampp\htdocs\siak\protected\components\UserIdentity.php(30): CActiveRecord->__get('id')
#2 C:\xampp\htdocs\siak\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\siak\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/siak/index.php/site/login
HTTP_REFERER=http://localhost/siak/index.php/site/login
---
2015/04/03 13:42:08 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/siak/index.php/user/admin
HTTP_REFERER=http://localhost/siak/index.php/user/2
---
2015/04/04 07:04:22 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\siak\protected\models\User.php:113)
Stack trace:
#0 C:\xampp\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#1 C:\xampp\yii\framework\zii\widgets\CListView.php(291): UserController->renderFile()
#2 C:\xampp\yii\framework\zii\widgets\CBaseListView.php(181): CListView->renderItems()
#3 unknown(0): CListView->renderSection()
#4 C:\xampp\yii\framework\zii\widgets\CBaseListView.php(164): preg_replace_callback()
#5 C:\xampp\yii\framework\zii\widgets\CBaseListView.php(149): CListView->renderContent()
#6 C:\xampp\yii\framework\web\CBaseController.php(181): CListView->run()
#7 C:\xampp\htdocs\siak\protected\views\user\index.php(20): UserController->widget()
#8 C:\xampp\yii\framework\web\CBaseController.php(126): require()
#9 C:\xampp\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#10 C:\xampp\yii\framework\web\CController.php(869): UserController->renderFile()
#11 C:\xampp\yii\framework\web\CController.php(782): UserController->renderPartial()
#12 C:\xampp\htdocs\siak\protected\controllers\UserController.php(132): UserController->render()
#13 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionIndex()
#14 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#15 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#16 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#17 C:\xampp\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#18 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#19 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#20 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#21 C:\xampp\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#22 C:\xampp\yii\framework\web\CWebApplication.php(282): UserController->run()
#23 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#24 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#25 C:\xampp\htdocs\siak\index.php(13): CWebApplication->run()
REQUEST_URI=/siak/index.php/user
in C:\xampp\htdocs\siak\protected\models\User.php (113)
in C:\xampp\htdocs\siak\protected\views\user\_view.php (20)
in C:\xampp\htdocs\siak\protected\views\user\index.php (20)
2015/04/04 07:05:12 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\siak\protected\models\User.php:113)
Stack trace:
#0 C:\xampp\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#1 C:\xampp\yii\framework\zii\widgets\CListView.php(291): UserController->renderFile()
#2 C:\xampp\yii\framework\zii\widgets\CBaseListView.php(181): CListView->renderItems()
#3 unknown(0): CListView->renderSection()
#4 C:\xampp\yii\framework\zii\widgets\CBaseListView.php(164): preg_replace_callback()
#5 C:\xampp\yii\framework\zii\widgets\CBaseListView.php(149): CListView->renderContent()
#6 C:\xampp\yii\framework\web\CBaseController.php(181): CListView->run()
#7 C:\xampp\htdocs\siak\protected\views\user\index.php(20): UserController->widget()
#8 C:\xampp\yii\framework\web\CBaseController.php(126): require()
#9 C:\xampp\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#10 C:\xampp\yii\framework\web\CController.php(869): UserController->renderFile()
#11 C:\xampp\yii\framework\web\CController.php(782): UserController->renderPartial()
#12 C:\xampp\htdocs\siak\protected\controllers\UserController.php(132): UserController->render()
#13 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionIndex()
#14 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#15 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#16 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#17 C:\xampp\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#18 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#19 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#20 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#21 C:\xampp\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#22 C:\xampp\yii\framework\web\CWebApplication.php(282): UserController->run()
#23 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#24 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#25 C:\xampp\htdocs\siak\index.php(13): CWebApplication->run()
REQUEST_URI=/siak/index.php/user
in C:\xampp\htdocs\siak\protected\models\User.php (113)
in C:\xampp\htdocs\siak\protected\views\user\_view.php (20)
in C:\xampp\htdocs\siak\protected\views\user\index.php (20)
2015/04/04 07:06:31 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\siak\protected\models\User.php:112)
Stack trace:
#0 C:\xampp\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#1 C:\xampp\yii\framework\zii\widgets\CListView.php(291): UserController->renderFile()
#2 C:\xampp\yii\framework\zii\widgets\CBaseListView.php(181): CListView->renderItems()
#3 unknown(0): CListView->renderSection()
#4 C:\xampp\yii\framework\zii\widgets\CBaseListView.php(164): preg_replace_callback()
#5 C:\xampp\yii\framework\zii\widgets\CBaseListView.php(149): CListView->renderContent()
#6 C:\xampp\yii\framework\web\CBaseController.php(181): CListView->run()
#7 C:\xampp\htdocs\siak\protected\views\user\index.php(20): UserController->widget()
#8 C:\xampp\yii\framework\web\CBaseController.php(126): require()
#9 C:\xampp\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#10 C:\xampp\yii\framework\web\CController.php(869): UserController->renderFile()
#11 C:\xampp\yii\framework\web\CController.php(782): UserController->renderPartial()
#12 C:\xampp\htdocs\siak\protected\controllers\UserController.php(132): UserController->render()
#13 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionIndex()
#14 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#15 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#16 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#17 C:\xampp\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#18 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#19 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#20 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#21 C:\xampp\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#22 C:\xampp\yii\framework\web\CWebApplication.php(282): UserController->run()
#23 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#24 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#25 C:\xampp\htdocs\siak\index.php(13): CWebApplication->run()
REQUEST_URI=/siak/index.php/user
in C:\xampp\htdocs\siak\protected\models\User.php (112)
in C:\xampp\htdocs\siak\protected\views\user\_view.php (20)
in C:\xampp\htdocs\siak\protected\views\user\index.php (20)
2015/04/04 07:17:36 [error] [php] Undefined variable: role (C:\xampp\htdocs\siak\protected\models\User.php:117)
Stack trace:
#0 C:\xampp\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#1 C:\xampp\yii\framework\zii\widgets\CListView.php(291): UserController->renderFile()
#2 C:\xampp\yii\framework\zii\widgets\CBaseListView.php(181): CListView->renderItems()
#3 unknown(0): CListView->renderSection()
#4 C:\xampp\yii\framework\zii\widgets\CBaseListView.php(164): preg_replace_callback()
#5 C:\xampp\yii\framework\zii\widgets\CBaseListView.php(149): CListView->renderContent()
#6 C:\xampp\yii\framework\web\CBaseController.php(181): CListView->run()
#7 C:\xampp\htdocs\siak\protected\views\user\index.php(20): UserController->widget()
#8 C:\xampp\yii\framework\web\CBaseController.php(126): require()
#9 C:\xampp\yii\framework\web\CBaseController.php(95): UserController->renderInternal()
#10 C:\xampp\yii\framework\web\CController.php(869): UserController->renderFile()
#11 C:\xampp\yii\framework\web\CController.php(782): UserController->renderPartial()
#12 C:\xampp\htdocs\siak\protected\controllers\UserController.php(132): UserController->render()
#13 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): UserController->actionIndex()
#14 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#15 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#16 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#17 C:\xampp\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#18 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#19 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#20 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#21 C:\xampp\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#22 C:\xampp\yii\framework\web\CWebApplication.php(282): UserController->run()
#23 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#24 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#25 C:\xampp\htdocs\siak\index.php(13): CWebApplication->run()
REQUEST_URI=/siak/index.php/user
in C:\xampp\htdocs\siak\protected\models\User.php (117)
in C:\xampp\htdocs\siak\protected\views\user\_view.php (20)
in C:\xampp\htdocs\siak\protected\views\user\index.php (20)
2015/04/04 07:38:58 [error] [exception.CException] exception 'CException' with message 'Property "UserController.id_role" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\siak\protected\controllers\UserController.php(33): CComponent->__get('id_role')
#1 C:\xampp\yii\framework\web\CController.php(1144): UserController->accessRules()
#2 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#3 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#4 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#5 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user')
#8 C:\xampp\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 C:\xampp\htdocs\siak\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/siak/index.php/user
---
